### ISSUE TITLE
希望添加繁體中文選項

### ISSUE THREAD

**Issue by Vik1n9** [cnrpman/kc_aircraftOptimize#4]
你好，我在NGA上看到這篇，試用後感覺不錯，希望可以添加繁體中文的介面選項。因為我對程序不了解，在文件中找到了簡中的文件，自作主張的改成了繁體中文版，部分用語修改貼合繁體中文環境。還請測試看看。

[TraditionalChinese.zip](https://github.com/cnrpman/kc_aircraftOptimize/files/651787/TraditionalChinese.zip)

**Comment by cnrpman** [comment]
这是隔壁连装炮的issue吗?

**Comment by cnrpman** [comment]
这是他们的repo，可以去那边发pull request
https://github.com/amatukaze/IntelligentNavalGun

**Comment by Vik1n9** [comment]
@cnrpman 尷尬了，發錯地方...抱歉！
